### PR TITLE
Update instructions with using alisw/system-deps/alice-build-machine

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@MichaelLettrich @atlantic777 why is the openjdk stuff needed? Is it due to JAlien? Can't we adapt the recipe, instead?

**Comment by Atlantic777** [comment]
OpenJDK is needed for bilding JAliEn Java components (JShell, JBox) in [alidist/jalien.sh](https://github.com/alisw/alidist/blob/master/jalien.sh). It looks like it's already using JDK from alidist.

**Comment by MichaelLettrich** [comment]
Hi I noticed we miss `mysql` as an additional dependency for alidist.  Can you add it to the deps?

**Comment by ktf** [comment]
Isn't it there?

https://github.com/alisw/homebrew-system-deps/blob/master/Formula/alice-build-machine.rb#L9

**Comment by ktf** [comment]
Ping?

**Pull request merged**
